// Generated by scripts/preview-capture.py. Do not edit by hand.
// Embedded in Preview metadata so captures identify their exact sources.
enum PreviewSourceFingerprint_73bbf1f9150d088c3b359b696673d973598ee215727fb105af891a913f82948e { static let value = "73bbf1f9150d088c3b359b696673d973598ee215727fb105af891a913f82948e" }
