#!/usr/bin/env python3
"""Prepare a build-specific SwiftUI Preview fingerprint and verify its capture."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

IOS_ROOT = Path(__file__).resolve().parents[1]
GENERATED = IOS_ROOT / "App" / "PreviewSourceFingerprint.generated.swift"
SOURCE_ROOTS = [IOS_ROOT / "App", IOS_ROOT / "Core" / "Sources", IOS_ROOT / "Infrastructure"]
REQUIRED_ANCHORS = {"sermon-title", "current-subtitle", "playback-toggle", "playback-more"}
TYPE_PREFIX = "PreviewSourceFingerprint_"


def current_fingerprint() -> str:
    digest = hashlib.sha256()
    for root in SOURCE_ROOTS:
        for path in sorted(root.rglob("*.swift")):
            if path == GENERATED:
                continue
            relative = path.relative_to(IOS_ROOT).as_posix().encode()
            digest.update(len(relative).to_bytes(4, "big"))
            digest.update(relative)
            contents = path.read_bytes()
            digest.update(len(contents).to_bytes(8, "big"))
            if path.name == "UIComponentPreviews.swift":
                contents = re.sub(rb"PreviewSourceFingerprint_[0-9a-f]{64}",
                                  b"PreviewSourceFingerprint_<BUILD_HASH>", contents)
            digest.update(contents)
    return digest.hexdigest()


def generated_fingerprint() -> str | None:
    if not GENERATED.exists():
        return None
    match = re.search(r"enum PreviewSourceFingerprint_([0-9a-f]{64})\s*\{", GENERATED.read_text())
    return match.group(1) if match else None


def prepare() -> int:
    fingerprint = current_fingerprint()
    source = (
        "// Generated by scripts/preview-capture.py. Do not edit by hand.\n"
        "// Embedded in Preview metadata so captures identify their exact sources.\n"
        f'enum {TYPE_PREFIX}{fingerprint} {{ static let value = "{fingerprint}" }}\n'
    )
    preview_file = IOS_ROOT / "App" / "UIComponentPreviews.swift"
    preview_contents = preview_file.read_text()
    preview_updated = re.sub(r"PreviewSourceFingerprint_(?:[0-9a-f]{64}|PLACEHOLDER)",
                              TYPE_PREFIX + fingerprint, preview_contents)
    preview_updated = re.sub(r"String\(describing: (PreviewSourceFingerprint_[0-9a-f]{64})\.self\)",
                             r"\1.value", preview_updated)
    if preview_updated == preview_contents and TYPE_PREFIX + fingerprint not in preview_contents:
        raise SystemExit("Preview source has no generated fingerprint reference")
    preview_file.write_text(preview_updated)
    previous = GENERATED.read_text() if GENERATED.exists() else None
    if previous != source:
        GENERATED.write_text(source)
    print(f"fingerprint={fingerprint}")
    print(f"updated={'yes' if previous != source or preview_updated != preview_contents else 'no'}")
    print(f"source={GENERATED}")
    return 0


def verify(metadata_path: Path, screenshot_path: Path | None, expected_device: str | None) -> int:
    try:
        capture = json.loads(metadata_path.read_text())
    except (OSError, json.JSONDecodeError) as error:
        print(f"ERROR: cannot read preview metadata: {error}", file=sys.stderr)
        return 2
    expected_fingerprint = current_fingerprint()
    compiled_fingerprint = generated_fingerprint()
    embedded = capture.get("sourceFingerprint")
    build_rows = [row for row in capture.get("records", []) if row.get("id") == "__build__"]
    build_label = build_rows[0].get("label") if build_rows else None
    if not compiled_fingerprint or compiled_fingerprint != expected_fingerprint:
        print("ERROR: generated build fingerprint is stale; run prepare and let Xcode rebuild Preview.", file=sys.stderr)
        return 3
    if embedded != expected_fingerprint or build_label != expected_fingerprint:
        print("ERROR: this Preview metadata belongs to a different source build; discard its screenshot.", file=sys.stderr)
        print(f"expected={expected_fingerprint} embedded={embedded} buildRecord={build_label}", file=sys.stderr)
        return 4
    if capture.get("schema") != "tongxing-preview-capture-v1":
        print(f"ERROR: unsupported metadata schema: {capture.get('schema')}", file=sys.stderr)
        return 5
    if expected_device and capture.get("requestedDevice") != expected_device:
        print(f"ERROR: expected device {expected_device!r}, got {capture.get('requestedDevice')!r}", file=sys.stderr)
        return 6
    anchors = {row.get("id") for row in capture.get("records", []) if row.get("kind") == "anchor"}
    missing = sorted(REQUIRED_ANCHORS - anchors)
    if missing:
        print(f"ERROR: capture is missing anchors: {', '.join(missing)}", file=sys.stderr)
        return 7
    screenshot_hash = None
    if screenshot_path:
        try:
            screenshot_hash = hashlib.sha256(screenshot_path.read_bytes()).hexdigest()
        except OSError as error:
            print(f"ERROR: cannot read screenshot: {error}", file=sys.stderr)
            return 8
    report = {
        "result": "verified",
        "scene": capture.get("scene"),
        "requestedDevice": capture.get("requestedDevice"),
        "sourceFingerprint": embedded,
        "operatingSystem": capture.get("operatingSystem"),
        "colorScheme": capture.get("colorScheme"),
        "dynamicTypeSize": capture.get("dynamicTypeSize"),
        "anchors": sorted(anchors),
        "metadata": str(metadata_path.resolve()),
        "screenshot": str(screenshot_path.resolve()) if screenshot_path else None,
        "screenshotSha256": screenshot_hash,
    }
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("prepare", help="regenerate the compile-time source fingerprint")
    check = subparsers.add_parser("verify", help="reject stale or mismatched preview captures")
    check.add_argument("--metadata", required=True, type=Path)
    check.add_argument("--screenshot", type=Path)
    check.add_argument("--device", help="require the named PreviewProvider destination")
    args = parser.parse_args()
    return prepare() if args.command == "prepare" else verify(args.metadata, args.screenshot, args.device)


if __name__ == "__main__":
    raise SystemExit(main())
