#!/usr/bin/env python3
"""Build browser-loadable playback simulation data from a POC report.

The generated file assigns `window.SERMON_PLAYBACK_SIMULATION`, which works both
from static hosting and when opening `web/index.html` directly with file://.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import importlib.util
import sys


POC_SCRIPT = Path(__file__).with_name("offline_live_sermon_subtitles.py")
SPEC = importlib.util.spec_from_file_location("offline_live_sermon_subtitles", POC_SCRIPT)
subtitle_mod = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
sys.modules[SPEC.name] = subtitle_mod
SPEC.loader.exec_module(subtitle_mod)


def main() -> int:
    args = parse_args()
    report = json.loads(args.report.read_text(encoding="utf-8"))
    output = select_output(report, args.lang)
    vtt_path = Path(output["live_aligned_vtt" if args.live_aligned else "local_vtt"])
    cues = subtitle_mod.parse_vtt(vtt_path.read_text(encoding="utf-8", errors="replace"))
    if args.merge_cues:
        cues = merge_progressive_cues(
            cues,
            max_segment_ms=args.max_segment_ms,
            max_segment_chars=args.max_segment_chars,
        )
    if args.max_segments:
        cues = cues[: args.max_segments]

    simulation = build_simulation(
        report=report,
        output=output,
        cues=cues,
        source_vtt=vtt_path,
        playback_speed=args.playback_speed,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_js(simulation), encoding="utf-8")
    print(json.dumps(summarize(simulation, args.out), ensure_ascii=False, indent=2))
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert an offline-live POC report into web playback simulation data."
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=Path("artifacts/offline-live-sermon-poc/report.json"),
        help="POC report.json generated by offline_live_sermon_subtitles.py.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("web/playback-simulation.generated.js"),
        help="Generated JS file loaded by the web prototype.",
    )
    parser.add_argument(
        "--lang",
        help="Preferred subtitle language. Defaults to zh-Hans, then en-orig, then en, then first output.",
    )
    parser.add_argument(
        "--local",
        dest="live_aligned",
        action="store_false",
        help="Use local sermon timeline instead of live-aligned timeline.",
    )
    parser.set_defaults(live_aligned=True)
    parser.add_argument(
        "--max-segments",
        type=int,
        default=80,
        help="Limit segments for lightweight browser simulation. Use 0 for all.",
    )
    parser.add_argument(
        "--playback-speed",
        type=float,
        default=18.0,
        help="Simulation speed multiplier. 18 means 18 seconds of sermon time per real second.",
    )
    parser.add_argument(
        "--no-merge-cues",
        dest="merge_cues",
        action="store_false",
        help="Keep raw VTT cues instead of merging progressive YouTube captions into readable segments.",
    )
    parser.add_argument(
        "--max-segment-ms",
        type=int,
        default=6000,
        help="Maximum merged segment duration for playback readability.",
    )
    parser.add_argument(
        "--max-segment-chars",
        type=int,
        default=220,
        help="Maximum merged segment text length for playback readability.",
    )
    parser.set_defaults(merge_cues=True)
    args = parser.parse_args()
    if args.max_segments == 0:
        args.max_segments = None
    return args


def select_output(report: dict[str, Any], lang: str | None) -> dict[str, Any]:
    outputs = report.get("outputs") or []
    if not outputs:
        raise SystemExit("POC report has no subtitle outputs.")

    preferences = [lang] if lang else ["zh-Hans", "zh", "en-orig", "en"]
    for preferred in preferences:
        if not preferred:
            continue
        for output in outputs:
            if output.get("lang") == preferred:
                return output
    return outputs[0]


def merge_progressive_cues(
    cues: list[Any],
    max_segment_ms: int = 6000,
    max_segment_chars: int = 220,
) -> list[Any]:
    increments = extract_incremental_cues(cues)
    if not increments:
        return []

    merged = []
    active_start = increments[0].start_ms
    active_end = increments[0].end_ms
    active_parts: list[str] = []

    for cue in increments:
        candidate_parts = active_parts + [cue.text]
        candidate_text = " ".join(candidate_parts).strip()
        duration_ms = cue.end_ms - active_start
        should_flush = bool(active_parts) and (
            duration_ms > max_segment_ms
            or len(candidate_text) > max_segment_chars
            or (ends_sentence(active_parts[-1]) and duration_ms >= 2500)
        )
        if should_flush:
            merged.append(
                subtitle_mod.Cue(
                    start_ms=active_start,
                    end_ms=active_end,
                    text=" ".join(active_parts).strip(),
                )
            )
            active_start = cue.start_ms
            active_parts = [cue.text]
        else:
            active_parts = candidate_parts
        active_end = cue.end_ms

    if active_parts:
        merged.append(
            subtitle_mod.Cue(
                start_ms=active_start,
                end_ms=active_end,
                text=" ".join(active_parts).strip(),
            )
        )
    return merged


def extract_incremental_cues(cues: list[Any]) -> list[Any]:
    increments = []
    previous_text = ""
    for cue in cues:
        text = newest_caption_line(cue.text)
        if not text or text == previous_text:
            continue
        increments.append(
            subtitle_mod.Cue(
                start_ms=cue.start_ms,
                end_ms=cue.end_ms,
                text=text,
            )
        )
        previous_text = text
    return increments


def newest_caption_line(text: str) -> str:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if not lines:
        return ""
    return lines[-1]


def ends_sentence(text: str) -> bool:
    return text.endswith((".", "?", "!", ":", ";"))


def build_simulation(
    report: dict[str, Any],
    output: dict[str, Any],
    cues: list[Any],
    source_vtt: Path,
    playback_speed: float,
) -> dict[str, Any]:
    lang = output.get("lang") or "unknown"
    has_zh = lang.startswith("zh")
    live = report.get("live") or {}
    sermon = report.get("sermon_candidate") or {}
    sermon_start = report.get("sermon_start") or {}

    segments = []
    for index, cue in enumerate(cues, start=1):
        source_text = cue.text.strip()
        zh_text = source_text if has_zh else "AI 中文待生成：" + source_text
        segments.append(
            {
                "id": f"sim_{index:04d}",
                "startMs": cue.start_ms,
                "endMs": cue.end_ms,
                "zh": zh_text,
                "draft": zh_text if has_zh else "正在根据英文字幕生成中文...",
                "en": source_text if not has_zh else "",
                "ref": detect_reference(source_text),
                "note": "来自直播链接 POC 的真实时间轴字幕。",
                "confidence": 86 if has_zh else 72,
                "translationStatus": "ready" if has_zh else "needs_translation",
            }
        )

    return {
        "schemaVersion": 1,
        "generatedFrom": "offline-live-sermon-poc",
        "mode": "live-link-playback-simulation",
        "playbackSpeed": playback_speed,
        "lang": lang,
        "sourceVtt": str(source_vtt),
        "live": {
            "id": live.get("id"),
            "title": live.get("title"),
            "url": live.get("url"),
            "durationSeconds": live.get("duration_seconds"),
        },
        "sermonCandidate": {
            "id": sermon.get("id"),
            "title": sermon.get("title"),
            "url": sermon.get("url"),
            "durationSeconds": sermon.get("duration_seconds"),
        },
        "sermonStart": sermon_start,
        "translationStatus": "ready" if has_zh else "needs_translation",
        "segments": segments,
    }


def detect_reference(text: str) -> str:
    lowered = text.lower()
    if "numbers" in lowered and "16" in lowered:
        return "Numbers 16"
    if "moses" in lowered or "aaron" in lowered:
        return "Numbers 16"
    if "jesus" in lowered:
        return "Jesus"
    return ""


def render_js(simulation: dict[str, Any]) -> str:
    payload = json.dumps(simulation, ensure_ascii=False, indent=2)
    return "window.SERMON_PLAYBACK_SIMULATION = " + payload + ";\n"


def summarize(simulation: dict[str, Any], out: Path) -> dict[str, Any]:
    segments = simulation.get("segments") or []
    first = segments[0] if segments else {}
    last = segments[-1] if segments else {}
    return {
        "status": "ok",
        "out": str(out),
        "lang": simulation.get("lang"),
        "translationStatus": simulation.get("translationStatus"),
        "segmentCount": len(segments),
        "firstStart": subtitle_mod.format_clock(first.get("startMs", 0)) if first else None,
        "lastEnd": subtitle_mod.format_clock(last.get("endMs", 0)) if last else None,
    }


if __name__ == "__main__":
    raise SystemExit(main())
