#!/usr/bin/env python3
"""Build scripture artifacts from eBible VPL data.

The POC keeps the browser payload small by publishing only referenced passages,
not a full Bible bundle. The Cloud Run backend can also include the full Bible
JSON generated by this script. Source data is the public-domain eBible
`cmn-cu89s_vpl.zip` archive.
"""

from __future__ import annotations

import argparse
import json
import re
import urllib.request
import zipfile
from dataclasses import dataclass
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Iterable


DEFAULT_SOURCE_URL = "https://ebible.org/Scriptures/cmn-cu89s_vpl.zip"
DEFAULT_DETAILS_URL = "https://ebible.org/find/details.php?id=cmn-cu89s"
DEFAULT_REFS = ["Numbers 16", "Numbers 16:48"]
JS_PREFIX = "window.SERMON_SCRIPTURE_INDEX = "

BOOKS = {
    "GEN": ("Genesis", "创世记"),
    "EXO": ("Exodus", "出埃及记"),
    "LEV": ("Leviticus", "利未记"),
    "NUM": ("Numbers", "民数记"),
    "DEU": ("Deuteronomy", "申命记"),
    "JOS": ("Joshua", "约书亚记"),
    "JDG": ("Judges", "士师记"),
    "RUT": ("Ruth", "路得记"),
    "1SA": ("1 Samuel", "撒母耳记上"),
    "2SA": ("2 Samuel", "撒母耳记下"),
    "1KI": ("1 Kings", "列王纪上"),
    "2KI": ("2 Kings", "列王纪下"),
    "1CH": ("1 Chronicles", "历代志上"),
    "2CH": ("2 Chronicles", "历代志下"),
    "EZR": ("Ezra", "以斯拉记"),
    "NEH": ("Nehemiah", "尼希米记"),
    "EST": ("Esther", "以斯帖记"),
    "JOB": ("Job", "约伯记"),
    "PSA": ("Psalms", "诗篇"),
    "PRO": ("Proverbs", "箴言"),
    "ECC": ("Ecclesiastes", "传道书"),
    "SOL": ("Song of Songs", "雅歌"),
    "ISA": ("Isaiah", "以赛亚书"),
    "JER": ("Jeremiah", "耶利米书"),
    "LAM": ("Lamentations", "耶利米哀歌"),
    "EZE": ("Ezekiel", "以西结书"),
    "DAN": ("Daniel", "但以理书"),
    "HOS": ("Hosea", "何西阿书"),
    "JOE": ("Joel", "约珥书"),
    "AMO": ("Amos", "阿摩司书"),
    "OBA": ("Obadiah", "俄巴底亚书"),
    "JON": ("Jonah", "约拿书"),
    "MIC": ("Micah", "弥迦书"),
    "NAH": ("Nahum", "那鸿书"),
    "HAB": ("Habakkuk", "哈巴谷书"),
    "ZEP": ("Zephaniah", "西番雅书"),
    "HAG": ("Haggai", "哈该书"),
    "ZEC": ("Zechariah", "撒迦利亚书"),
    "MAL": ("Malachi", "玛拉基书"),
    "MAT": ("Matthew", "马太福音"),
    "MAR": ("Mark", "马可福音"),
    "LUK": ("Luke", "路加福音"),
    "JOH": ("John", "约翰福音"),
    "ACT": ("Acts", "使徒行传"),
    "ROM": ("Romans", "罗马书"),
    "1CO": ("1 Corinthians", "哥林多前书"),
    "2CO": ("2 Corinthians", "哥林多后书"),
    "GAL": ("Galatians", "加拉太书"),
    "EPH": ("Ephesians", "以弗所书"),
    "PHI": ("Philippians", "腓立比书"),
    "COL": ("Colossians", "歌罗西书"),
    "1TH": ("1 Thessalonians", "帖撒罗尼迦前书"),
    "2TH": ("2 Thessalonians", "帖撒罗尼迦后书"),
    "1TI": ("1 Timothy", "提摩太前书"),
    "2TI": ("2 Timothy", "提摩太后书"),
    "TIT": ("Titus", "提多书"),
    "PHM": ("Philemon", "腓利门书"),
    "HEB": ("Hebrews", "希伯来书"),
    "JAM": ("James", "雅各书"),
    "1PE": ("1 Peter", "彼得前书"),
    "2PE": ("2 Peter", "彼得后书"),
    "1JO": ("1 John", "约翰一书"),
    "2JO": ("2 John", "约翰二书"),
    "3JO": ("3 John", "约翰三书"),
    "JUD": ("Jude", "犹大书"),
    "REV": ("Revelation", "启示录"),
}

BOOK_ALIASES = {
    code.lower(): code
    for code in BOOKS
}
for code, (english, chinese) in BOOKS.items():
    BOOK_ALIASES[english.lower()] = code
    BOOK_ALIASES[chinese] = code
BOOK_ALIASES.update(
    {
        "num": "NUM",
        "psalm": "PSA",
        "psalms": "PSA",
        "song of solomon": "SOL",
        "song of songs": "SOL",
        "1 sam": "1SA",
        "2 sam": "2SA",
        "1 kings": "1KI",
        "2 kings": "2KI",
        "1 chron": "1CH",
        "2 chron": "2CH",
        "1 cor": "1CO",
        "2 cor": "2CO",
        "1 thess": "1TH",
        "2 thess": "2TH",
        "1 tim": "1TI",
        "2 tim": "2TI",
        "1 pet": "1PE",
        "2 pet": "2PE",
        "1 john": "1JO",
        "2 john": "2JO",
        "3 john": "3JO",
    }
)


@dataclass(frozen=True)
class Verse:
    book: str
    chapter: int
    verse: int
    text: str


@dataclass(frozen=True)
class Reference:
    raw: str
    book: str
    chapter: int
    start_verse: int | None = None
    end_verse: int | None = None

    @property
    def key(self) -> str:
        english = BOOKS[self.book][0]
        if self.start_verse is None:
            return f"{english} {self.chapter}"
        if self.end_verse and self.end_verse != self.start_verse:
            return f"{english} {self.chapter}:{self.start_verse}-{self.end_verse}"
        return f"{english} {self.chapter}:{self.start_verse}"


def main() -> int:
    args = parse_args()
    archive = Path(args.zip) if args.zip else download_source(args.source_url)
    verses = load_vpl_archive(archive)
    refs = [parse_reference(ref) for ref in args.ref]
    payload = build_payload(verses, refs, args.source_url)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_js(payload), encoding="utf-8")
    result = {"status": "ok", "out": str(args.out), "references": sorted(payload["references"])}
    if args.full_out:
        full_payload = build_full_bible_payload(verses, args.source_url)
        args.full_out.parent.mkdir(parents=True, exist_ok=True)
        args.full_out.write_text(
            json.dumps(full_payload, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        result["fullOut"] = str(args.full_out)
        result["books"] = len(full_payload["books"])
        result["verses"] = full_payload["verseCount"]
    print(json.dumps(result, ensure_ascii=False))
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--zip", help="Existing cmn-cu89s_vpl.zip path. If omitted, download from eBible.")
    parser.add_argument("--source-url", default=DEFAULT_SOURCE_URL)
    parser.add_argument("--out", type=Path, default=Path("web/scripture-cmn-cu89s.generated.js"))
    parser.add_argument("--full-out", type=Path, help="Optional full Bible JSON output for Cloud Run or GCS.")
    parser.add_argument("--ref", action="append", default=[], help="Reference to include, e.g. 'Numbers 16'.")
    args = parser.parse_args()
    if not args.ref:
        args.ref = DEFAULT_REFS
    return args


def download_source(url: str) -> Path:
    tmp = TemporaryDirectory()
    path = Path(tmp.name) / "cmn-cu89s_vpl.zip"
    urllib.request.urlretrieve(url, path)
    # Keep the temporary directory alive for the duration of this process.
    download_source._tmp = tmp  # type: ignore[attr-defined]
    return path


def load_vpl_archive(path: Path) -> list[Verse]:
    with zipfile.ZipFile(path) as archive:
        names = [name for name in archive.namelist() if name.endswith("_vpl.txt")]
        if not names:
            raise SystemExit(f"No *_vpl.txt file found in {path}")
        text = archive.read(names[0]).decode("utf-8-sig")
    return parse_vpl_text(text.splitlines())


def parse_vpl_text(lines: Iterable[str]) -> list[Verse]:
    verses = []
    pattern = re.compile(r"^([1-3]?[A-Z]{2,3})\s+(\d+):(\d+)\s+(.+)$")
    for line in lines:
        match = pattern.match(line.strip())
        if not match:
            continue
        book, chapter, verse, text = match.groups()
        verses.append(Verse(book=book, chapter=int(chapter), verse=int(verse), text=normalize_text(text)))
    return verses


def normalize_text(text: str) -> str:
    return re.sub(r"\s+", " ", text.replace("\u3000", " ")).strip()


def parse_reference(value: str) -> Reference:
    clean = value.strip()
    match = re.match(r"^(.+?)\s+(\d+)(?::(\d+)(?:-(\d+))?)?$", clean, re.IGNORECASE)
    if not match:
        raise SystemExit(f"Unsupported scripture reference: {value}")
    book_name, chapter, start, end = match.groups()
    book = BOOK_ALIASES.get(book_name.strip().lower()) or BOOK_ALIASES.get(book_name.strip())
    if not book:
        raise SystemExit(f"Unsupported scripture book: {book_name}")
    return Reference(
        raw=value,
        book=book,
        chapter=int(chapter),
        start_verse=int(start) if start else None,
        end_verse=int(end) if end else int(start) if start else None,
    )


def build_payload(verses: list[Verse], refs: list[Reference], source_url: str) -> dict:
    by_ref = {}
    for ref in refs:
        ref_verses = select_verses(verses, ref)
        if not ref_verses:
            raise SystemExit(f"No verses matched {ref.raw}")
        by_ref[ref.key] = reference_payload(ref, ref_verses)
    return {
        "schemaVersion": 1,
        "translation": translation_metadata(source_url),
        "references": by_ref,
    }


def translation_metadata(source_url: str) -> dict:
    return {
        "id": "cmn-cu89s",
        "nameZh": "新标点和合本（简体）",
        "nameEn": "Chinese Union Version (simplified)",
        "sourceName": "eBible.org",
        "sourceUrl": DEFAULT_DETAILS_URL,
        "downloadUrl": source_url,
        "license": "Public Domain",
        "sourceUpdated": "2021-10-15",
    }


def build_full_bible_payload(verses: list[Verse], source_url: str) -> dict:
    chapters: dict[str, dict[str, list[dict[str, int | str]]]] = {}
    present_books = []
    for verse in verses:
        chapters.setdefault(verse.book, {}).setdefault(str(verse.chapter), []).append(
            {"verse": verse.verse, "text": verse.text}
        )
        if verse.book not in present_books:
            present_books.append(verse.book)
    books = [
        {
            "code": code,
            "nameEn": BOOKS[code][0],
            "nameZh": BOOKS[code][1],
            "chapters": len(chapters.get(code, {})),
        }
        for code in present_books
    ]
    return {
        "schemaVersion": 1,
        "translation": translation_metadata(source_url),
        "books": books,
        "chapters": chapters,
        "verseCount": len(verses),
    }


def select_verses(verses: list[Verse], ref: Reference) -> list[Verse]:
    selected = [
        verse for verse in verses
        if verse.book == ref.book and verse.chapter == ref.chapter
    ]
    if ref.start_verse is None:
        return selected
    end = ref.end_verse or ref.start_verse
    return [verse for verse in selected if ref.start_verse <= verse.verse <= end]


def reference_payload(ref: Reference, verses: list[Verse]) -> dict:
    english, chinese = BOOKS[ref.book]
    verse_label = f"{ref.chapter}" if ref.start_verse is None else (
        f"{ref.chapter}:{ref.start_verse}-{ref.end_verse}"
        if ref.end_verse and ref.end_verse != ref.start_verse
        else f"{ref.chapter}:{ref.start_verse}"
    )
    return {
        "badge": "经文",
        "title": f"{chinese} {verse_label}",
        "source": "中文圣经：新标点和合本（简体） · eBible.org cmn-cu89s · Public Domain",
        "canonicalRef": ref.key,
        "book": english,
        "bookZh": chinese,
        "chapter": ref.chapter,
        "verses": [
            {"verse": f"{ref.chapter}:{verse.verse}", "text": verse.text}
            for verse in verses
        ],
    }

def render_js(payload: dict) -> str:
    return JS_PREFIX + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n"


if __name__ == "__main__":
    raise SystemExit(main())
