#!/usr/bin/env python3
"""Build browser-loadable playback simulation data from a POC report.

The generated file assigns `window.SERMON_PLAYBACK_SIMULATION`, which works both
from static hosting and when opening `web/index.html` directly with file://.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

import importlib.util
import sys


POC_SCRIPT = Path(__file__).with_name("offline_live_sermon_subtitles.py")
SCRIPTURE_SCRIPT = Path(__file__).with_name("build_scripture_index.py")
REPO_ROOT = Path(__file__).resolve().parents[1]
SECRET_RESOURCE_RE = re.compile(
    r"^projects/[^/\s]+/secrets/[^/\s]+(?:/versions/[^/\s]+)?$"
)
SPEC = importlib.util.spec_from_file_location("offline_live_sermon_subtitles", POC_SCRIPT)
subtitle_mod = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
sys.modules[SPEC.name] = subtitle_mod
SPEC.loader.exec_module(subtitle_mod)

SCRIPTURE_SPEC = importlib.util.spec_from_file_location("build_scripture_index", SCRIPTURE_SCRIPT)
scripture_mod = importlib.util.module_from_spec(SCRIPTURE_SPEC)
assert SCRIPTURE_SPEC.loader is not None
sys.modules[SCRIPTURE_SPEC.name] = scripture_mod
SCRIPTURE_SPEC.loader.exec_module(scripture_mod)

ENGLISH_CHAPTER_WORDS = {
    "one": 1,
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "seven": 7,
    "eight": 8,
    "nine": 9,
    "ten": 10,
    "eleven": 11,
    "twelve": 12,
    "thirteen": 13,
    "fourteen": 14,
    "fifteen": 15,
    "sixteen": 16,
    "seventeen": 17,
    "eighteen": 18,
    "nineteen": 19,
    "twenty": 20,
}
CHINESE_DIGITS = {
    "零": 0,
    "一": 1,
    "二": 2,
    "两": 2,
    "三": 3,
    "四": 4,
    "五": 5,
    "六": 6,
    "七": 7,
    "八": 8,
    "九": 9,
}


def main() -> int:
    args = parse_args()
    if args.api_key_secret:
        validate_secret_resource_name(args.api_key_secret)
    report = json.loads(args.report.read_text(encoding="utf-8"))
    output = select_output(report, args.lang)
    vtt_path = Path(output["live_aligned_vtt" if args.live_aligned else "local_vtt"])
    cues = subtitle_mod.parse_vtt(vtt_path.read_text(encoding="utf-8", errors="replace"))
    if args.merge_cues:
        cues = merge_progressive_cues(
            cues,
            max_segment_ms=args.max_segment_ms,
            max_segment_chars=args.max_segment_chars,
        )
    if args.max_segments:
        cues = cues[: args.max_segments]

    simulation = build_simulation(
        report=report,
        output=output,
        cues=cues,
        source_vtt=vtt_path,
        playback_speed=args.playback_speed,
        api_key_secret=args.api_key_secret,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_js(simulation), encoding="utf-8")
    print(json.dumps(summarize(simulation, args.out), ensure_ascii=False, indent=2))
    return 0


def validate_secret_resource_name(value: str) -> None:
    if not SECRET_RESOURCE_RE.fullmatch(value):
        raise SystemExit(
            "--api-key-secret must be a Google Secret Manager resource name like "
            "projects/PROJECT_ID/secrets/SECRET_ID/versions/latest. Do not pass raw API key material."
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert an offline-live POC report into web playback simulation data."
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=Path("artifacts/offline-live-sermon-poc/report.json"),
        help="POC report.json generated by offline_live_sermon_subtitles.py.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("web/playback-simulation.generated.js"),
        help="Generated JS file loaded by the web prototype.",
    )
    parser.add_argument(
        "--lang",
        help="Preferred subtitle language. Defaults to zh-Hans, then en-orig, then en, then first output.",
    )
    parser.add_argument(
        "--local",
        dest="live_aligned",
        action="store_false",
        help="Use local sermon timeline instead of live-aligned timeline.",
    )
    parser.set_defaults(live_aligned=True)
    parser.add_argument(
        "--max-segments",
        type=int,
        default=80,
        help="Limit segments for lightweight browser simulation. Use 0 for all.",
    )
    parser.add_argument(
        "--playback-speed",
        type=float,
        default=18.0,
        help="Simulation speed multiplier. 18 means 18 seconds of sermon time per real second.",
    )
    parser.add_argument(
        "--api-key-secret",
        help="Optional Google Secret Manager resource name for the translation/model API key.",
    )
    parser.add_argument(
        "--no-merge-cues",
        dest="merge_cues",
        action="store_false",
        help="Keep raw VTT cues instead of merging progressive YouTube captions into readable segments.",
    )
    parser.add_argument(
        "--max-segment-ms",
        type=int,
        default=6000,
        help="Maximum merged segment duration for playback readability.",
    )
    parser.add_argument(
        "--max-segment-chars",
        type=int,
        default=220,
        help="Maximum merged segment text length for playback readability.",
    )
    parser.set_defaults(merge_cues=True)
    args = parser.parse_args()
    if args.max_segments == 0:
        args.max_segments = None
    return args


def select_output(report: dict[str, Any], lang: str | None) -> dict[str, Any]:
    outputs = report.get("outputs") or []
    if not outputs:
        raise SystemExit("POC report has no subtitle outputs.")

    preferences = [lang] if lang else ["zh-Hans", "zh", "en-orig", "en"]
    for preferred in preferences:
        if not preferred:
            continue
        for output in outputs:
            if output.get("lang") == preferred:
                return output
    return outputs[0]


def merge_progressive_cues(
    cues: list[Any],
    max_segment_ms: int = 6000,
    max_segment_chars: int = 220,
) -> list[Any]:
    increments = extract_incremental_cues(cues)
    if not increments:
        return []

    merged = []
    active_start = increments[0].start_ms
    active_end = increments[0].end_ms
    active_parts: list[str] = []

    for cue in increments:
        candidate_parts = active_parts + [cue.text]
        candidate_text = " ".join(candidate_parts).strip()
        duration_ms = cue.end_ms - active_start
        should_flush = bool(active_parts) and (
            duration_ms > max_segment_ms
            or len(candidate_text) > max_segment_chars
            or (ends_sentence(active_parts[-1]) and duration_ms >= 2500)
        )
        if should_flush:
            merged.append(
                subtitle_mod.Cue(
                    start_ms=active_start,
                    end_ms=active_end,
                    text=" ".join(active_parts).strip(),
                )
            )
            active_start = cue.start_ms
            active_parts = [cue.text]
        else:
            active_parts = candidate_parts
        active_end = cue.end_ms

    if active_parts:
        merged.append(
            subtitle_mod.Cue(
                start_ms=active_start,
                end_ms=active_end,
                text=" ".join(active_parts).strip(),
            )
        )
    return merged


def extract_incremental_cues(cues: list[Any]) -> list[Any]:
    increments = []
    previous_text = ""
    for cue in cues:
        text = newest_caption_line(cue.text)
        if not text or text == previous_text:
            continue
        increments.append(
            subtitle_mod.Cue(
                start_ms=cue.start_ms,
                end_ms=cue.end_ms,
                text=text,
            )
        )
        previous_text = text
    return increments


def newest_caption_line(text: str) -> str:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if not lines:
        return ""
    return lines[-1]


def ends_sentence(text: str) -> bool:
    return text.endswith((".", "?", "!", ":", ";"))


def build_simulation(
    report: dict[str, Any],
    output: dict[str, Any],
    cues: list[Any],
    source_vtt: Path,
    playback_speed: float,
    api_key_secret: str | None = None,
) -> dict[str, Any]:
    lang = output.get("lang") or "unknown"
    has_zh = lang.startswith("zh")
    live = report.get("live") or {}
    sermon = report.get("sermon_candidate") or {}
    sermon_start = report.get("sermon_start") or {}
    caption_source = report.get("caption_source") or {}
    sermon_title = sermon.get("title") or live.get("title") or "Untitled sermon"

    segments = []
    for index, cue in enumerate(cues, start=1):
        source_text = cue.text.strip()
        zh_text = source_text if has_zh else "AI 中文待生成：" + source_text
        references = detect_references(source_text)
        segments.append(
            {
                "id": f"sim_{index:04d}",
                "startMs": cue.start_ms,
                "endMs": cue.end_ms,
                "zh": zh_text,
                "draft": zh_text if has_zh else "正在根据英文字幕生成中文...",
                "en": source_text if not has_zh else "",
                "ref": references[0]["canonicalRef"] if references else "",
                "refs": references,
                "note": "来自直播链接 POC 的真实时间轴字幕。",
                "confidence": 86 if has_zh else 72,
                "translationStatus": "ready" if has_zh else "needs_translation",
            }
        )

    return {
        "schemaVersion": 1,
        "generatedFrom": "offline-live-sermon-poc",
        "mode": "live-link-playback-simulation",
        "playbackSpeed": playback_speed,
        "lang": lang,
        "offlineSourceKind": caption_source.get("kind") or output.get("source_kind") or "unknown",
        "sourceVtt": safe_display_path(source_vtt),
        "sermonTitle": sermon_title,
        "secrets": {
            "apiKeyMaterialIncluded": False,
            "secretResourceNamesIncluded": False,
            "serverSideSecretConfigured": bool(api_key_secret),
        },
        "live": {
            "id": live.get("id"),
            "title": live.get("title"),
            "url": live.get("url"),
            "durationSeconds": live.get("duration_seconds"),
        },
        "sermonCandidate": {
            "id": sermon.get("id"),
            "title": sermon.get("title"),
            "url": sermon.get("url"),
            "durationSeconds": sermon.get("duration_seconds"),
        },
        "sermonStart": sermon_start,
        "translationStatus": "ready" if has_zh else "needs_translation",
        "scriptureReferences": merge_segment_references(segments),
        "segments": segments,
    }


def safe_display_path(path: Path) -> str:
    resolved = path.resolve()
    try:
        return resolved.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return resolved.name


def detect_reference(text: str) -> str:
    references = detect_references(text)
    return references[0]["canonicalRef"] if references else ""


def detect_references(text: str) -> list[dict[str, Any]]:
    matches: list[dict[str, Any]] = []
    seen = set()
    for book_code, alias in scripture_aliases():
        for chapter in chapters_for_alias(text, alias):
            book = scripture_mod.BOOKS[book_code]
            canonical = f"{book[0]} {chapter}"
            if canonical in seen:
                continue
            seen.add(canonical)
            matches.append(
                {
                    "canonicalRef": canonical,
                    "book": book[0],
                    "bookZh": book[1],
                    "chapter": chapter,
                    "title": f"{book[1]} {chapter}",
                }
            )
    return matches


def scripture_aliases() -> list[tuple[str, str]]:
    aliases = []
    for book_code, (english, chinese) in scripture_mod.BOOKS.items():
        aliases.extend([(book_code, english), (book_code, chinese)])
    aliases.extend(
        [
            ("NUM", "Num"),
            ("PSA", "Psalm"),
            ("1CO", "1 Cor"),
            ("2CO", "2 Cor"),
            ("1JO", "1 John"),
            ("2JO", "2 John"),
            ("3JO", "3 John"),
        ]
    )
    return sorted(aliases, key=lambda item: len(item[1]), reverse=True)


def chapters_for_alias(text: str, alias: str) -> list[int]:
    escaped = re.escape(alias)
    if contains_cjk(alias):
        pattern = re.compile(rf"{escaped}\s*([0-9一二两三四五六七八九十百]+)\s*(?:章|:|：)?")
    else:
        pattern = re.compile(
            rf"\b(?:book\s+of\s+)?{escaped}\b\s*(?:chapter\s+)?([0-9]+|{'|'.join(ENGLISH_CHAPTER_WORDS)})\b",
            re.IGNORECASE,
        )
    chapters = []
    for match in pattern.finditer(text):
        parsed = parse_chapter_number(match.group(1))
        if parsed:
            chapters.append(parsed)
    return chapters


def contains_cjk(value: str) -> bool:
    return any("\u4e00" <= char <= "\u9fff" for char in value)


def parse_chapter_number(value: str) -> int | None:
    if value.isdigit():
        return int(value)
    lowered = value.lower()
    if lowered in ENGLISH_CHAPTER_WORDS:
        return ENGLISH_CHAPTER_WORDS[lowered]
    if all(char in CHINESE_DIGITS or char in {"十", "百"} for char in value):
        return chinese_number_to_int(value)
    return None


def chinese_number_to_int(value: str) -> int | None:
    if not value:
        return None
    if value.isdigit():
        return int(value)
    if "百" in value:
        left, _, right = value.partition("百")
        hundreds = CHINESE_DIGITS.get(left, 1 if not left else 0)
        tail = chinese_number_to_int(right) if right else 0
        return hundreds * 100 + (tail or 0)
    if "十" in value:
        left, _, right = value.partition("十")
        tens = CHINESE_DIGITS.get(left, 1 if not left else 0)
        ones = CHINESE_DIGITS.get(right, 0) if right else 0
        return tens * 10 + ones
    total = 0
    for char in value:
        if char not in CHINESE_DIGITS:
            return None
        total = total * 10 + CHINESE_DIGITS[char]
    return total


def merge_segment_references(segments: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_ref = {}
    for segment in segments:
        for ref in segment.get("refs", []):
            by_ref.setdefault(ref["canonicalRef"], ref)
    return list(by_ref.values())


def render_js(simulation: dict[str, Any]) -> str:
    payload = json.dumps(simulation, ensure_ascii=False, indent=2)
    return "window.SERMON_PLAYBACK_SIMULATION = " + payload + ";\n"


def summarize(simulation: dict[str, Any], out: Path) -> dict[str, Any]:
    segments = simulation.get("segments") or []
    first = segments[0] if segments else {}
    last = segments[-1] if segments else {}
    return {
        "status": "ok",
        "out": str(out),
        "lang": simulation.get("lang"),
        "translationStatus": simulation.get("translationStatus"),
        "segmentCount": len(segments),
        "firstStart": subtitle_mod.format_clock(first.get("startMs", 0)) if first else None,
        "lastEnd": subtitle_mod.format_clock(last.get("endMs", 0)) if last else None,
    }


if __name__ == "__main__":
    raise SystemExit(main())
