import Foundation
import Testing
@testable import TongxingCore

struct FingerprintTestAudio {
    struct Random {
        var seed: UInt32
        mutating func next() -> Double {
            seed = seed &* 1_664_525 &+ 1_013_904_223
            return Double(seed) / 4_294_967_296
        }
    }
    // Same deterministic procedural events as web/fingerprint.test.mjs. The
    // checked-in index was generated by that JS engine, not by this Swift code.
    static func signal(_ seconds: Double, seed: UInt32 = 414_923, sampleRate: Double = 8000) -> [Float] {
        var random = Random(seed: seed), output = [Float](repeating: 0, count: Int((seconds * sampleRate).rounded()))
        var start = 0.0
        while start < seconds {
            let length = 0.2 + random.next() * 0.2
            let frequencies = (0..<5).map { _ in 230 + random.next() * 2700 }
            let phases = frequencies.map { _ in random.next() * .pi * 2 }
            var i = Int(floor(start * sampleRate))
            while Double(i) < min(Double(output.count), (start + length) * sampleRate) {
                let t = Double(i) / sampleRate - start, envelope = pow(sin(.pi * t / length), 2)
                for f in frequencies.indices {
                    output[i] = Float(Double(output[i]) + 0.09 * envelope * sin(2 * .pi * frequencies[f] * t + phases[f]))
                }
                i += 1
            }
            start += 0.18 + random.next() * 0.19
        }
        return output
    }
    static func fixtureData() throws -> Data {
        let url = try #require(Bundle.module.url(forResource: "fingerprint.synthetic", withExtension: "json", subdirectory: "Fixtures"))
        return try Data(contentsOf: url)
    }
    static func fixture() throws -> FingerprintIndex { try FingerprintIndex.decode(fixtureData()) }
    static func slice(_ samples: [Float], at offset: Double, seconds: Double = 8, rate: Double = 8000) -> [Float] {
        let start = Int((offset * rate).rounded()), count = Int((seconds * rate).rounded())
        return Array(samples[start..<(start + count)])
    }
}

struct FingerprintTests {
    @Test func webGeneratedIndexLocatesArbitraryOffsetsAndPreservesPausedSafeResultContract() throws {
        let index = try FingerprintTestAudio.fixture(), reference = FingerprintTestAudio.signal(50)
        for (offset, gain) in [(0.0, 1.0), (4.123, 0.015), (22.371, -0.3), (42.0, 1.0)] {
            let sample = FingerprintTestAudio.slice(reference, at: offset).map { Float(Double($0) * gain) }
            let result = try FingerprintMatcher.match(samples: sample, sampleRate: 8000, index: index)
            #expect(result.matched, "\(offset): \(result.diagnostics)")
            #expect(abs((result.offsetSeconds ?? -1) - offset) <= 0.064)
            #expect(result.diagnostics.consistency?.passed == true)
            #expect(result.diagnostics.confidenceKind == "evidence-score-not-probability")
        }
    }

    @Test func microphoneRateResamplingAndNoiseRetainTheOriginalQueryClock() throws {
        let index = try FingerprintTestAudio.fixture()
        let highRate = FingerprintTestAudio.signal(24, sampleRate: 48_000)
        let result = try FingerprintMatcher.match(samples: FingerprintTestAudio.slice(highRate, at: 8.723, rate: 48_000), sampleRate: 48_000, index: index)
        #expect(result.matched); #expect(abs((result.offsetSeconds ?? -1) - 8.723) <= 0.064)
        var sample = FingerprintTestAudio.slice(FingerprintTestAudio.signal(50), at: 15.777)
        var random = FingerprintTestAudio.Random(seed: 49302)
        let energy = sample.reduce(0.0) { $0 + Double($1) * Double($1) }
        let amplitude = sqrt(energy / Double(sample.count)) * sqrt(3) * pow(10, -5.0 / 20)
        for i in sample.indices { sample[i] = Float((Double(sample[i]) + (random.next() * 2 - 1) * amplitude) * 0.2) }
        let noisy = try FingerprintMatcher.match(samples: sample, sampleRate: 8000, index: index)
        #expect(noisy.matched); #expect(abs((noisy.offsetSeconds ?? -1) - 15.777) <= 0.064)
    }

    @Test func silenceToneNoiseUnrelatedAudioAndContradictorySplicesNeverOfferASeek() throws {
        let index = try FingerprintTestAudio.fixture(), reference = FingerprintTestAudio.signal(50)
        var random = FingerprintTestAudio.Random(seed: 774222)
        let tone = (0..<64000).map { Float(0.3 * sin(2 * .pi * 440 * Double($0) / 8000)) }
        let noise = (0..<64000).map { _ in Float(random.next() * 0.2 - 0.1) }
        var splice = FingerprintTestAudio.slice(reference, at: 3.131)
        splice.replaceSubrange(32000..<64000, with: FingerprintTestAudio.slice(reference, at: 28.443, seconds: 4))
        let queries = [[Float](repeating: 0, count: 64000), tone, noise, FingerprintTestAudio.signal(8, seed: 824373),
            Array(FingerprintTestAudio.slice(reference, at: 13.411).reversed()), splice]
        for query in queries {
            let result = try FingerprintMatcher.match(samples: query, sampleRate: 8000, index: index)
            #expect(!result.matched, "\(result.diagnostics)"); #expect(result.offsetSeconds == nil); #expect(result.confidence == 0)
        }
    }

    @Test func repeatedReferencePostingsRemainAmbiguous() throws {
        let original = try FingerprintTestAudio.fixture()
        var pairs: [(UInt32, UInt32)] = []
        for (hash, times) in original.lookup {
            for time in times { pairs.append((hash, UInt32(time))); pairs.append((hash, UInt32(time + 1875))) }
        }
        pairs.sort { $0.0 == $1.0 ? $0.1 < $1.1 : $0.0 < $1.0 }
        var bytes = Data()
        for (hash, time) in pairs {
            var littleHash = hash.littleEndian, littleTime = time.littleEndian
            withUnsafeBytes(of: &littleHash) { bytes.append(contentsOf: $0) }
            withUnsafeBytes(of: &littleTime) { bytes.append(contentsOf: $0) }
        }
        var object = try #require(JSONSerialization.jsonObject(with: FingerprintTestAudio.fixtureData()) as? [String: Any])
        object["durationSeconds"] = 110; object["landmarkCount"] = original.landmarkCount * 2
        object["pairCount"] = pairs.count; object["postings"] = bytes.base64EncodedString()
        let repeated = try FingerprintIndex.decode(JSONSerialization.data(withJSONObject: object))
        let result = try FingerprintMatcher.match(samples: FingerprintTestAudio.slice(FingerprintTestAudio.signal(50), at: 15.777), sampleRate: 8000, index: repeated)
        #expect(!result.matched); #expect(result.diagnostics.reason == "ambiguous-offset")
    }

    @Test func invalidSamplesAndMalformedIndexesFailClosed() throws {
        let index = try FingerprintTestAudio.fixture(), sample = FingerprintTestAudio.signal(8)
        for rate in [0.0, 7999, 192001, .infinity, .nan] {
            #expect(throws: (any Error).self) { try FingerprintMatcher.match(samples: sample, sampleRate: rate, index: index) }
        }
        for count in [0, 4 * 8000, 6 * 8000, 21 * 8000] {
            #expect(throws: (any Error).self) { try FingerprintMatcher.match(samples: [Float](repeating: 0, count: count), sampleRate: 8000, index: index) }
        }
        var bad = sample; bad[300] = .nan
        #expect(throws: (any Error).self) { try FingerprintMatcher.match(samples: bad, sampleRate: 8000, index: index) }
        let original = try #require(JSONSerialization.jsonObject(with: FingerprintTestAudio.fixtureData()) as? [String: Any])
        for (key, value) in [("schemaVersion", "other" as Any), ("durationSeconds", 0), ("landmarkCount", -1),
                             ("pairCount", 2), ("postings", "truncated"), ("method", "other")] {
            var object = original; object[key] = value
            #expect(throws: (any Error).self) { try FingerprintIndex.decode(JSONSerialization.data(withJSONObject: object)) }
        }
        var object = original, algorithm = original["algorithm"] as! [String: Any]
        algorithm["fftSize"] = 2048; object["algorithm"] = algorithm
        #expect(throws: (any Error).self) { try FingerprintIndex.decode(JSONSerialization.data(withJSONObject: object)) }
    }

    @Test func cancelledMatchingTaskDoesNotReturnASeek() async throws {
        let index = try FingerprintTestAudio.fixture(), samples = FingerprintTestAudio.signal(8)
        let task = Task.detached {
            withUnsafeCurrentTask { $0?.cancel() }
            return try FingerprintMatcher.match(samples: samples, sampleRate: 8000, index: index)
        }
        do { _ = try await task.value; Issue.record("Cancelled matching returned a result") }
        catch { #expect(error is CancellationError) }
    }
}
